[package]
name = "execute-test-v2"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tempfile = "3"
uuid = { version = "1.17.0", features = ["v4"] }
